export type ForgedWeapon = {
  custo: string | undefined;
  id_equipamento: number;
  fkTipoEquipamento?: string;
  qeNome?: string;
  qePeso?: string;
  qeCustoPo?: string;
  qeCustoPp?: string;
  qeCustoPc?: string;
  qeDano?: string;
  fkConceito?: string;
  fkDano?: 'piercing' | 'slashing' | 'bludgeoning';
  bnDano?: number;
  bnCa?: number;
  bnBa?: number;
  bnCarga?: number;
  qeAlcDips?: string;
  qeAlcArr?: string;
  qeProp?: string;
  qeObs?: string;
  qeStatus?: string;
  qeAutor?: string;
  fkFonte?: string;
  qeImg?: string;
  sufixo: Map<string, string>;
  propriedades: string;
  qtde?: number;
  bolt?: boolean;
  bolt_small?: boolean;
  arrow?: boolean;
  polearm?: boolean;
  two_handed?: boolean;
  versatile?: boolean;
};
